### PR TITLE
Addition of the "UNIVERSAL" BaubleType

### PR DESCRIPTION
**Pull request by Gordon-Frohman**
Can be placed in any Bauble slot
Required for Twilight Forest backport, so I could make charms wearable in any bauble slot

### CODE REVIEW

**Comment by Gordon-Frohman** [comment]
Well, it doesn't compile, but it seems not to be an issue of my code

**Comment by miozune** [comment]
Fixed build

**Comment by Gordon-Frohman** [comment]
Thanks!

**Comment by ghost** [comment]
it would be awesome if someone added feature to set more than 4 baubles, just like Baubles-expanded

**Comment by Gordon-Frohman** [comment]
It would, but my goal here was to backport a Twilight Forest feature, not to add anything to Baubles

**Review by Caedis — APPROVED** [review]
Looks good

**Pull request merged**
