### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by Gordon-Frohman**
Fixed a bug where you could equip an entire stack of items with Shift+click
Added an option to unequip items with Shift+click
P.S.
Sorry for the messy commits: had a conflict between web and desktop GitHub

### CODE REVIEW

**Comment by Caedis** [comment]
Can you rename the `par2` and `j` variables to be a more descriptive?

**Comment by Gordon-Frohman** [comment]
> Can you rename the `par2` and `j` variables to be a more descriptive?

Well, I wasn't the one who created those variables, but if you want me to, I certainly can.

**Comment by Gordon-Frohman** [comment]
Done
Hopefully that'll make it easier to read

**Review by Caedis — APPROVED** [review]

**Comment by Caedis** [comment]
Thanks, makes it a lot easier to follow

**Comment by Gordon-Frohman** [comment]
> Thanks, makes it a lot easier to follow

You're welcome
And thank you for approving)

**Pull request merged**
